# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM golang:1.24-alpine

# Install necessary packages
RUN apk add --no-cache git

WORKDIR /app

# Copy the go module files
COPY go/votars-mcp/go.mod go/votars-mcp/go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the application code
COPY go/votars-mcp/ ./

# Build the MCP server binary
RUN go build -o votars-mcp .

# Expose port 8080 for SSE mode
EXPOSE 8080

# Default command: run in stdio mode
CMD ["./votars-mcp", "-t", "stdio"]
